name: multi2convai
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python>=3.6
  - pip
  - numpy
  - nltk
  - scikit-learn
  - pytorch
  - transformers
  - pip:
     - -e .  # install git checkout of multi2convai in editable mode

  # DEVELOPMENT ONLY PACKAGES
  - jupyterlab
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - nbstripout
  - sphinx
  - recommonmark
